server:
  port: 8080  # 서버 포트 설정

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/walk_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Shfksto1!

  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate 중 선택 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-doc