spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST:${SPRING_DATASOURCE_HOST}}:${RDS_PORT:3306}/${RDS_DB:walk_web}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&connectionTimeZone=UTC
    username: ${RDS_USER:${SPRING_DATASOURCE_USERNAME}}
    password: ${RDS_PW:${SPRING_DATASOURCE_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

